/* 
 * Copyright 2014 ClinRisk Ltd.
 * 
 * This file is part of QDiabetesAmpBlind (http://qdiabetes.org/amputation-blindness, http://svn.clinrisk.co.uk/opensource/qdiabetes).
 * 
 * QDiabetesAmpBlind is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QDiabetesAmpBlind is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QDiabetesAmpBlind.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qdiabetes, faithfully implements QDiabetesAmpBlind.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qdiabetes.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q92_blindness_9_1.xml
 * STATA dta time stamp: 16 Jan 2015 13:01
 * This file was created on: Mon  9 Nov 2015 09:52:44 GMT
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q92_blindness_9_1.h>
#include <clinrisk/utils.h>

static double blindness_male_raw(
int age,int b_prolif_maculo,int b_renal,int b_type1,int diabetes_years2,double hba1c,double rati,double sbp,int surv,double town
)
{
	double survivor[16] = {
		0,
		0.998661279678345,
		0.997423827648163,
		0.996265351772308,
		0.995044469833374,
		0.993644714355469,
		0.992300927639008,
		0.990893006324768,
		0.989402353763580,
		0.987855434417725,
		0.986233174800873,
		0.984356284141541,
		0.982878088951111,
		0.981105446815491,
		0.979238629341125,
		0.976939022541046
	};

	/* The conditional arrays */

	double Iduration[5] = {
		0,
		0.3375060132871872700000000,
		0.3511063513991332700000000,
		0.4537070569036014700000000,
		0.7367735454630960400000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_2 = pow(dage,2)*log(dage);
	double age_1 = pow(dage,2);
	double dhba1c = hba1c;
	dhba1c=dhba1c/100;
	double hba1c_2 = pow(dhba1c,-2)*log(dhba1c);
	double hba1c_1 = pow(dhba1c,-2);
	double dsbp = sbp;
	dsbp=dsbp/100;
	double sbp_1 = dsbp;
	double sbp_2 = pow(dsbp,2);

	/* Centring the continuous variables */

	age_1 = age_1 - 35.293895721435547;
	age_2 = age_2 - 62.888603210449219;
	hba1c_1 = hba1c_1 - 2.464975595474243;
	hba1c_2 = hba1c_2 - -1.111928224563599;
	rati = rati - 4.521738052368164;
	sbp_1 = sbp_1 - 1.383464217185974;
	sbp_2 = sbp_2 - 1.913973212242127;
	town = town - 0.000000000000000;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Iduration[diabetes_years2];

	/* Sum from continuous values */

	a += age_1 * -0.0531092087069124290000000;
	a += age_2 * 0.0428971532620619070000000;
	a += hba1c_1 * -0.3423402222189455600000000;
	a += hba1c_2 * -0.2262902099129215600000000;
	a += rati * 0.0304587031379472580000000;
	a += sbp_1 * -2.7537667415105016000000000;
	a += sbp_2 * 1.0330490824440557000000000;
	a += town * 0.0569938441163678130000000;

	/* Sum from boolean values */

	a += b_prolif_maculo * 1.0756576702031289000000000;
	a += b_renal * 0.9452143872417053700000000;
	a += b_type1 * 0.3671384747549474900000000;

	/* Sum from interaction terms */

	a += age_1 * b_renal * 0.0299641398433647020000000;
	a += age_2 * b_renal * -0.0266145203920317400000000;

	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int blindness_male_validation(
int age,int b_prolif_maculo,int b_renal,int b_type1,int diabetes_years2,double hba1c,double rati,double sbp,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,16,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (16,84)\n",errorBufSize);
	}
	if (!is_boolean(b_prolif_maculo)) {
		ok=0;
		strlcat(errorBuf,"error: b_prolif_maculo must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type1)) {
		ok=0;
		strlcat(errorBuf,"error: b_type1 must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(diabetes_years2,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: diabetes_years2 must be in range (0,4)\n",errorBufSize);
	}
	if (!d_in_range(hba1c,20,240)) {
		ok=0;
		strlcat(errorBuf,"error: hba1c must be in range (20,240)\n",errorBufSize);
	}
	if (!d_in_range(rati,1,12)) {
		ok=0;
		strlcat(errorBuf,"error: rati must be in range (1,12)\n",errorBufSize);
	}
	if (!d_in_range(sbp,70,250)) {
		ok=0;
		strlcat(errorBuf,"error: sbp must be in range (70,250)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,10)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,10)\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double blindness_male(
int age,int b_prolif_maculo,int b_renal,int b_type1,int diabetes_years2,double hba1c,double rati,double sbp,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = blindness_male_validation(age,b_prolif_maculo,b_renal,b_type1,diabetes_years2,hba1c,rati,sbp,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return blindness_male_raw(age,b_prolif_maculo,b_renal,b_type1,diabetes_years2,hba1c,rati,sbp,surv,town);
}
