/* 
 * Copyright 2014 ClinRisk Ltd.
 * 
 * This file is part of QDiabetesAmpBlind (http://qdiabetes.org/amputation-blindness, http://svn.clinrisk.co.uk/opensource/qdiabetes).
 * 
 * QDiabetesAmpBlind is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QDiabetesAmpBlind is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QDiabetesAmpBlind.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qdiabetes, faithfully implements QDiabetesAmpBlind.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qdiabetes.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q92_amputation_9_0.xml
 * STATA dta time stamp: 16 Jan 2015 13:01
 * This file was created on: Mon  9 Nov 2015 09:52:05 GMT
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q92_amputation_9_0.h>
#include <clinrisk/utils.h>

static double amputation_female_raw(
int age,int b_CCF,int b_pvd,int b_ra,int b_renal,int diabetes_years2,int ethrisk,double hba1c,double sbp,int smoke_cat,int surv,double town
)
{
	double survivor[16] = {
		0,
		0.999478995800018,
		0.999041616916656,
		0.998605787754059,
		0.998089790344238,
		0.997565746307373,
		0.997074007987976,
		0.996516287326813,
		0.995766103267670,
		0.994947493076324,
		0.994030773639679,
		0.993156015872955,
		0.992274403572083,
		0.991240143775940,
		0.990119278430939,
		0.989208817481995
	};

	/* The conditional arrays */

	double Iduration[5] = {
		0,
		0.4616746820397087400000000,
		0.5271292192907646200000000,
		0.8614510719613133200000000,
		1.1949599969789171000000000
	};
	double Iethrisk[10] = {
		0,
		0,
		-0.8224352511347856600000000,
		-0.3267305057774836900000000,
		-1.2526296377540833000000000,
		-0.3564338213455192600000000,
		-0.1340814131061524600000000,
		-0.0843970530858196430000000,
		-0.7006785773867746400000000,
		-0.3635732470477335800000000
	};
	double Ismoke[5] = {
		0,
		0.0760970470440550520000000,
		0.4615824605801990300000000,
		0.4543512446313404100000000,
		0.6383923205327095600000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dhba1c = hba1c;
	dhba1c=dhba1c/100;
	double hba1c_2 = pow(dhba1c,3)*log(dhba1c);
	double hba1c_1 = pow(dhba1c,3);
	double dsbp = sbp;
	dsbp=dsbp/100;
	double sbp_1 = pow(dsbp,-1);
	double sbp_2 = pow(dsbp,-.5);

	/* Centring the continuous variables */

	age = age - 61.496467590332031;
	hba1c_1 = hba1c_1 - 0.239701583981514;
	hba1c_2 = hba1c_2 - -0.114126756787300;
	sbp_1 = sbp_1 - 0.717780888080597;
	sbp_2 = sbp_2 - 0.847219467163086;
	town = town - 0.000000000000000;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Iduration[diabetes_years2];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age * 0.0125467095917233990000000;
	a += hba1c_1 * 1.1169285924216117000000000;
	a += hba1c_2 * -1.8087132823689427000000000;
	a += sbp_1 * 15.2890007571027780000000000;
	a += sbp_2 * -27.5315418567665130000000000;
	a += town * 0.0187264151590038410000000;

	/* Sum from boolean values */

	a += b_CCF * 0.5805776570624784400000000;
	a += b_pvd * 1.4483885143025534000000000;
	a += b_ra * 0.4057055269570911700000000;
	a += b_renal * 0.9846858598974856900000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int amputation_female_validation(
int age,int b_CCF,int b_pvd,int b_ra,int b_renal,int diabetes_years2,int ethrisk,double hba1c,double sbp,int smoke_cat,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,16,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (16,84)\n",errorBufSize);
	}
	if (!is_boolean(b_CCF)) {
		ok=0;
		strlcat(errorBuf,"error: b_CCF must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_pvd)) {
		ok=0;
		strlcat(errorBuf,"error: b_pvd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_ra)) {
		ok=0;
		strlcat(errorBuf,"error: b_ra must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(diabetes_years2,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: diabetes_years2 must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!d_in_range(hba1c,20,240)) {
		ok=0;
		strlcat(errorBuf,"error: hba1c must be in range (20,240)\n",errorBufSize);
	}
	if (!d_in_range(sbp,70,250)) {
		ok=0;
		strlcat(errorBuf,"error: sbp must be in range (70,250)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,10)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,10)\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double amputation_female(
int age,int b_CCF,int b_pvd,int b_ra,int b_renal,int diabetes_years2,int ethrisk,double hba1c,double sbp,int smoke_cat,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = amputation_female_validation(age,b_CCF,b_pvd,b_ra,b_renal,diabetes_years2,ethrisk,hba1c,sbp,smoke_cat,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return amputation_female_raw(age,b_CCF,b_pvd,b_ra,b_renal,diabetes_years2,ethrisk,hba1c,sbp,smoke_cat,surv,town);
}
