/* 
 * Copyright 2011 ClinRisk Ltd.
 * 
 * This file is part of QThrombosis (http://qthrombosis.org, http://svn.clinrisk.co.uk/opensource/qthrombosis).
 * 
 * QThrombosis is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QThrombosis is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QThrombosis.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qthrombosis, faithfully implements QThrombosis.
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qthrombosis.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q66_vte_xml_20_vte_1.xml
 * STATA dta time stamp: 20 Mar 2011 13:10
 * This file was created on: Mon 15 Aug 2011 18:51:10 BST
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q66_vte_xml_20_vte_1.h>
#include <clinrisk/utils.h>

static double vte_male_raw(
int age,int antipsychotics_current,int b_CCF,int b_anycancer,int b_copd,int b_ibd,int b_renal,int b_varicosevein,double bmi,int smoke_cat,int surv,int z1_admit
)
{
	double survivor[6] = {
		0,
		0.999382615089417,
		0.998721301555634,
		0.998039424419403,
		0.997391760349274,
		0.996659278869629
	};

	/* The conditional arrays */

	double Ismoke[5] = {
		0,
		0.0598794437047157070000000,
		0.1969634293531217800000000,
		0.3122591446032924600000000,
		0.3972767241864175200000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,3);
	double age_2 = pow(dage,3)*log(dage);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-2);
	double bmi_2 = pow(dbmi,-2)*log(dbmi);

	/* Centring the continuous variables */

	age_1 = age_1 - 101.348503112792970;
	age_2 = age_2 - 156.028213500976560;
	bmi_1 = bmi_1 - 0.142084553837776;
	bmi_2 = bmi_2 - 0.138627126812935;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 0.0313211810690797590000000;
	a += age_2 * -0.0122517555622382920000000;
	a += bmi_1 * 4.9329818770360587000000000;
	a += bmi_2 * -20.7628515850941970000000000;

	/* Sum from boolean values */

	a += antipsychotics_current * 0.6089150603052773100000000;
	a += b_CCF * 0.2844367087524523100000000;
	a += b_anycancer * 0.7804608566556066100000000;
	a += b_copd * 0.4806535066546788200000000;
	a += b_ibd * 0.4048328650785730800000000;
	a += b_renal * 0.6502298708643805500000000;
	a += b_varicosevein * 0.3253840764585496100000000;
	a += z1_admit * 0.6595321569689306400000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int vte_male_validation(
int age,int antipsychotics_current,int b_CCF,int b_anycancer,int b_copd,int b_ibd,int b_renal,int b_varicosevein,double bmi,int smoke_cat,int surv,int z1_admit,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,25,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (25,84)\n",errorBufSize);
	}
	if (!is_boolean(antipsychotics_current)) {
		ok=0;
		strlcat(errorBuf,"error: antipsychotics_current must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_CCF)) {
		ok=0;
		strlcat(errorBuf,"error: b_CCF must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_anycancer)) {
		ok=0;
		strlcat(errorBuf,"error: b_anycancer must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_copd)) {
		ok=0;
		strlcat(errorBuf,"error: b_copd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_ibd)) {
		ok=0;
		strlcat(errorBuf,"error: b_ibd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_varicosevein)) {
		ok=0;
		strlcat(errorBuf,"error: b_varicosevein must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,5)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,5)\n",errorBufSize);
	}
	if (!is_boolean(z1_admit)) {
		ok=0;
		strlcat(errorBuf,"error: z1_admit must be in range (0,1)\n",errorBufSize);
	}
	return ok;
}

double vte_male(
int age,int antipsychotics_current,int b_CCF,int b_anycancer,int b_copd,int b_ibd,int b_renal,int b_varicosevein,double bmi,int smoke_cat,int surv,int z1_admit,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = vte_male_validation(age,antipsychotics_current,b_CCF,b_anycancer,b_copd,b_ibd,b_renal,b_varicosevein,bmi,smoke_cat,surv,z1_admit,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return vte_male_raw(age,antipsychotics_current,b_CCF,b_anycancer,b_copd,b_ibd,b_renal,b_varicosevein,bmi,smoke_cat,surv,z1_admit);
}
