/* 
 * Copyright 2014 ClinRisk Ltd.
 * 
 * This file is part of QBleed (http://qbleed.org, http://svn.clinrisk.co.uk/opensource/qbleed).
 * 
 * QBleed is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QBleed is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QBleed.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qbleed, faithfully implements QBleed.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qbleed.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q81_anticoagbleed_8_27_3_0.xml
 * STATA dta time stamp: 25 Jan 2014 20:52
 * This file was created on: Tue 29 Jul 2014 14:05:50 BST
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q81_anticoagbleed_8_27_3_0.h>
#include <clinrisk/utils.h>

static double Q81_anticoagbleed_8_27_3_female_raw(
int age,int alcohol_cat6,int b_AF,int b_anticonvulsant,int b_antidepressant,int b_antiplat,int b_liverpancreas,int b_platlet,int b_treatedhyp,int b_varices,double bmi,int ethrisk,int exp_anticoagulant,int prior_anybleed,int smoke_cat,int surv,double town
)
{
	double survivor[6] = {
		0,
		0.999858736991882,
		0,
		0,
		0,
		0.999163031578064
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		-0.0394385990438745680000000,
		0.0306313349864260900000000,
		0.0455556863122008400000000,
		0.7541806093255716300000000,
		0.9617076514239487600000000
	};
	double Iethrisk[10] = {
		0,
		0,
		0.0212937247416742430000000,
		-0.0826994770829479200000000,
		0.4705528351546407500000000,
		-0.0621202775726895990000000,
		0.1340566924081883800000000,
		0.1835421052327345400000000,
		0.3556636758661720900000000,
		0.1279071592221652200000000
	};
	double Ismoke[5] = {
		0,
		0.1171448628027752800000000,
		0.5886149318711029200000000,
		0.7530521510611186700000000,
		0.8644616876126838300000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,-1);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-2);
	double bmi_2 = pow(dbmi,-2)*log(dbmi);

	/* Centring the continuous variables */

	age_1 = age_1 - 0.216344222426414;
	age_2 = age_2 - 98.756134033203125;
	bmi_1 = bmi_1 - 0.151425197720528;
	bmi_2 = bmi_2 - 0.142919912934303;
	town = town - 0.234209924936295;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * -9.3955388761190211000000000;
	a += age_2 * 0.0030401499750880522000000;
	a += bmi_1 * 1.2970985752730677000000000;
	a += bmi_2 * 4.8508426067467596000000000;
	a += town * 0.0276469041059274580000000;

	/* Sum from boolean values */

	a += b_AF * 0.1537804603125871000000000;
	a += b_anticonvulsant * 0.7893567437957221800000000;
	a += b_antidepressant * 0.2688569414180234700000000;
	a += b_antiplat * 0.2687227594062988100000000;
	a += b_liverpancreas * 0.6526977316652463600000000;
	a += b_platlet * 0.4854148355882955700000000;
	a += b_treatedhyp * 0.0624715044742381390000000;
	a += b_varices * 1.1700583013028483000000000;
	a += exp_anticoagulant * 1.2862341402265320000000000;
	a += prior_anybleed * 0.2867598802850193100000000;

	/* Sum from interaction terms */

	a += age_1 * exp_anticoagulant * -8.0967928247780385000000000;
	a += age_2 * exp_anticoagulant * -0.0018692245502041349000000;

	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int Q81_anticoagbleed_8_27_3_female_validation(
int age,int alcohol_cat6,int b_AF,int b_anticonvulsant,int b_antidepressant,int b_antiplat,int b_liverpancreas,int b_platlet,int b_treatedhyp,int b_varices,double bmi,int ethrisk,int exp_anticoagulant,int prior_anybleed,int smoke_cat,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,21,99)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (21,99)\n",errorBufSize);
	}
	if (!i_in_range(alcohol_cat6,0,5)) {
		ok=0;
		strlcat(errorBuf,"error: alcohol_cat6 must be in range (0,5)\n",errorBufSize);
	}
	if (!is_boolean(b_AF)) {
		ok=0;
		strlcat(errorBuf,"error: b_AF must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_anticonvulsant)) {
		ok=0;
		strlcat(errorBuf,"error: b_anticonvulsant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_antidepressant)) {
		ok=0;
		strlcat(errorBuf,"error: b_antidepressant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_antiplat)) {
		ok=0;
		strlcat(errorBuf,"error: b_antiplat must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_liverpancreas)) {
		ok=0;
		strlcat(errorBuf,"error: b_liverpancreas must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_platlet)) {
		ok=0;
		strlcat(errorBuf,"error: b_platlet must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_treatedhyp)) {
		ok=0;
		strlcat(errorBuf,"error: b_treatedhyp must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_varices)) {
		ok=0;
		strlcat(errorBuf,"error: b_varices must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!is_boolean(exp_anticoagulant)) {
		ok=0;
		strlcat(errorBuf,"error: exp_anticoagulant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(prior_anybleed)) {
		ok=0;
		strlcat(errorBuf,"error: prior_anybleed must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if ( !(surv==1 || surv==5) ) {
		ok=0;
		strlcat(errorBuf,"error: surv must be 1 or 5\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double Q81_anticoagbleed_8_27_3_female(
int age,int alcohol_cat6,int b_AF,int b_anticonvulsant,int b_antidepressant,int b_antiplat,int b_liverpancreas,int b_platlet,int b_treatedhyp,int b_varices,double bmi,int ethrisk,int exp_anticoagulant,int prior_anybleed,int smoke_cat,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = Q81_anticoagbleed_8_27_3_female_validation(age,alcohol_cat6,b_AF,b_anticonvulsant,b_antidepressant,b_antiplat,b_liverpancreas,b_platlet,b_treatedhyp,b_varices,bmi,ethrisk,exp_anticoagulant,prior_anybleed,smoke_cat,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return Q81_anticoagbleed_8_27_3_female_raw(age,alcohol_cat6,b_AF,b_anticonvulsant,b_antidepressant,b_antiplat,b_liverpancreas,b_platlet,b_treatedhyp,b_varices,bmi,ethrisk,exp_anticoagulant,prior_anybleed,smoke_cat,surv,town);
}
