/* 
 * Copyright 2014 ClinRisk Ltd.
 * 
 * This file is part of QDiabetesAmpBlind (http://qdiabetes.org/amputation-blindness, http://svn.clinrisk.co.uk/opensource/qdiabetes).
 * 
 * QDiabetesAmpBlind is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QDiabetesAmpBlind is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QDiabetesAmpBlind.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qdiabetes, faithfully implements QDiabetesAmpBlind.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qdiabetes.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q92_blindness_9_0.xml
 * STATA dta time stamp: 16 Jan 2015 13:01
 * This file was created on: Mon  9 Nov 2015 09:52:33 GMT
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q92_blindness_9_0.h>
#include <clinrisk/utils.h>

static double blindness_female_raw(
int age,int b_prolif_maculo,int b_renal,int b_type1,int diabetes_years2,double hba1c,double rati,double sbp,int surv,double town
)
{
	double survivor[16] = {
		0,
		0.998451650142670,
		0.996975183486938,
		0.995326638221741,
		0.993605315685272,
		0.991926789283752,
		0.989969015121460,
		0.988248527050018,
		0.986282110214233,
		0.984297513961792,
		0.982246279716492,
		0.980445325374603,
		0.978188157081604,
		0.975826263427734,
		0.973409891128540,
		0.971289992332459
	};

	/* The conditional arrays */

	double Iduration[5] = {
		0,
		0.3101081522393051000000000,
		0.4103915605124617800000000,
		0.5420096687393100000000000,
		0.7727524162991977800000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_2 = pow(dage,2)*log(dage);
	double age_1 = pow(dage,2);
	double dhba1c = hba1c;
	dhba1c=dhba1c/100;
	double hba1c_1 = pow(dhba1c,2);
	double hba1c_2 = pow(dhba1c,2)*log(dhba1c);

	/* Centring the continuous variables */

	age_1 = age_1 - 37.680530548095703;
	age_2 = age_2 - 68.374023437500000;
	hba1c_1 = hba1c_1 - 0.386333167552948;
	hba1c_2 = hba1c_2 - -0.183712080121040;
	rati = rati - 4.195173740386963;
	sbp = sbp - 139.283508300781250;
	town = town - 0.000000000000000;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Iduration[diabetes_years2];

	/* Sum from continuous values */

	a += age_1 * -0.0657569527265517010000000;
	a += age_2 * 0.0467957306077368340000000;
	a += hba1c_1 * 0.7440027760556119400000000;
	a += hba1c_2 * -0.9737385319688620600000000;
	a += rati * 0.0557909319489447720000000;
	a += sbp * 0.0035558072808973213000000;
	a += town * 0.0382178494747925230000000;

	/* Sum from boolean values */

	a += b_prolif_maculo * 0.9837456754221842700000000;
	a += b_renal * 0.3970793635114743800000000;
	a += b_type1 * 0.4050160977267797700000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int blindness_female_validation(
int age,int b_prolif_maculo,int b_renal,int b_type1,int diabetes_years2,double hba1c,double rati,double sbp,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,16,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (16,84)\n",errorBufSize);
	}
	if (!is_boolean(b_prolif_maculo)) {
		ok=0;
		strlcat(errorBuf,"error: b_prolif_maculo must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type1)) {
		ok=0;
		strlcat(errorBuf,"error: b_type1 must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(diabetes_years2,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: diabetes_years2 must be in range (0,4)\n",errorBufSize);
	}
	if (!d_in_range(hba1c,20,240)) {
		ok=0;
		strlcat(errorBuf,"error: hba1c must be in range (20,240)\n",errorBufSize);
	}
	if (!d_in_range(rati,1,12)) {
		ok=0;
		strlcat(errorBuf,"error: rati must be in range (1,12)\n",errorBufSize);
	}
	if (!d_in_range(sbp,70,250)) {
		ok=0;
		strlcat(errorBuf,"error: sbp must be in range (70,250)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,10)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,10)\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double blindness_female(
int age,int b_prolif_maculo,int b_renal,int b_type1,int diabetes_years2,double hba1c,double rati,double sbp,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = blindness_female_validation(age,b_prolif_maculo,b_renal,b_type1,diabetes_years2,hba1c,rati,sbp,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return blindness_female_raw(age,b_prolif_maculo,b_renal,b_type1,diabetes_years2,hba1c,rati,sbp,surv,town);
}
