/* 
 * Copyright 2014 ClinRisk Ltd.
 * 
 * This file is part of QThrombosis-2014 (http://qthrombosis.org, http://svn.clinrisk.co.uk/opensource/qthrombosis).
 * 
 * QThrombosis-2014 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QThrombosis-2014 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QThrombosis-2014.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qthrombosis, faithfully implements QThrombosis-2014.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qthrombosis.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q88_vte_2014_1.xml
 * STATA dta time stamp: 17 Jun 2014 22:53
 * This file was created on: Fri 11 Sep 2015 10:36:39 BST
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q88_vte_2014_1.h>
#include <clinrisk/utils.h>

static double vte_male_raw(
int age,int b_CCF,int b_admit,int b_antipsychotic,int b_anycancer,int b_copd,int b_ibd,int b_renal,int b_varicosevein,double bmi,int smoke_cat,int surv,double town
)
{
	double survivor[6] = {
		0,
		0.999353885650635,
		0.998677849769592,
		0.997899055480957,
		0.997062921524048,
		0.996150791645050
	};

	/* The conditional arrays */

	double Ismoke[5] = {
		0,
		0.0732279786093590760000000,
		0.2090383346821476100000000,
		0.2352668393059219600000000,
		0.2891966714984033300000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,3);
	double age_2 = pow(dage,3)*log(dage);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-2);
	double bmi_2 = pow(dbmi,-2)*log(dbmi);

	/* Centring the continuous variables */

	age_1 = age_1 - 98.675651550292969;
	age_2 = age_2 - 151.034210205078120;
	bmi_1 = bmi_1 - 0.141316697001457;
	bmi_2 = bmi_2 - 0.138260856270790;
	town = town - 0.217443808913231;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 0.0338786420157746950000000;
	a += age_2 * -0.0134355813870903100000000;
	a += bmi_1 * 8.0146563036940002000000000;
	a += bmi_2 * -26.8544544727998090000000000;
	a += town * 0.0118277945308610120000000;

	/* Sum from boolean values */

	a += b_CCF * 0.2945134928144034200000000;
	a += b_admit * 0.3732581842634301000000000;
	a += b_antipsychotic * 0.3992543441751350600000000;
	a += b_anycancer * 0.6337244810913510400000000;
	a += b_copd * 0.3463179824315285600000000;
	a += b_ibd * 0.4879618121644490000000000;
	a += b_renal * 0.4871456661811857100000000;
	a += b_varicosevein * 0.4131507059810912200000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int vte_male_validation(
int age,int b_CCF,int b_admit,int b_antipsychotic,int b_anycancer,int b_copd,int b_ibd,int b_renal,int b_varicosevein,double bmi,int smoke_cat,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,25,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (25,84)\n",errorBufSize);
	}
	if (!is_boolean(b_CCF)) {
		ok=0;
		strlcat(errorBuf,"error: b_CCF must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_admit)) {
		ok=0;
		strlcat(errorBuf,"error: b_admit must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_antipsychotic)) {
		ok=0;
		strlcat(errorBuf,"error: b_antipsychotic must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_anycancer)) {
		ok=0;
		strlcat(errorBuf,"error: b_anycancer must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_copd)) {
		ok=0;
		strlcat(errorBuf,"error: b_copd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_ibd)) {
		ok=0;
		strlcat(errorBuf,"error: b_ibd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_varicosevein)) {
		ok=0;
		strlcat(errorBuf,"error: b_varicosevein must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,5)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,5)\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double vte_male(
int age,int b_CCF,int b_admit,int b_antipsychotic,int b_anycancer,int b_copd,int b_ibd,int b_renal,int b_varicosevein,double bmi,int smoke_cat,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = vte_male_validation(age,b_CCF,b_admit,b_antipsychotic,b_anycancer,b_copd,b_ibd,b_renal,b_varicosevein,bmi,smoke_cat,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return vte_male_raw(age,b_CCF,b_admit,b_antipsychotic,b_anycancer,b_copd,b_ibd,b_renal,b_varicosevein,bmi,smoke_cat,surv,town);
}
