/* 
 * Copyright 2012 ClinRisk Ltd.
 * 
 * This file is part of QFracture-2012 (http://qfracture.org, http://svn.clinrisk.co.uk/qfracture).
 * 
 * QFracture-2012 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QFracture-2012 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QFracture-2012.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/qfracture, faithfully implements QFracture-2012.
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/qfracture.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q74_qnof_2012_2_0.xml
 * STATA dta time stamp: 1 Mar 2012 11:21
 * This file was created on: Mon  5 Mar 2012 11:14:32 GMT
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q74_qnof_2012_2_0.h>
#include <clinrisk/utils.h>

static double nof_female_raw(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_fracture4,int b_hrt_oest,int b_liver,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int smoke_cat,int surv
)
{
	double survivor[19] = {
		0,
		0.999910116195679,
		0.999807536602020,
		0.999693453311920,
		0.999558806419373,
		0.999401748180389,
		0.999216556549072,
		0.999019324779511,
		0.998785734176636,
		0.998515725135803,
		0.998187243938446,
		0.997814238071442,
		0.997377276420593,
		0.996870458126068,
		0.996309578418732,
		0.995707631111145,
		0.995065331459045,
		0.994253218173981,
		0.993366956710815
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		-0.1286446642326926600000000,
		-0.0997737785682041020000000,
		0.0542649888398008330000000,
		0.4431543152512633600000000,
		0.6633035785016026000000000
	};
	double Iethrisk[10] = {
		0,
		0,
		-0.5145680493118204300000000,
		-0.7809041138976792200000000,
		-0.5845922612624047100000000,
		-0.5418443926512139800000000,
		-1.3017049081958438000000000,
		-2.3170037513024733000000000,
		-1.0406259543469680000000000,
		-0.7087921758363630000000000
	};
	double Ismoke[5] = {
		0,
		0.0794965480333605090000000,
		0.2835141126936128200000000,
		0.3121458383725539400000000,
		0.4798404329218986000000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,2);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-2);

	/* Centring the continuous variables */

	age_1 = age_1 - 26.304763793945313;
	age_2 = age_2 - 134.912322998046870;
	bmi_1 = bmi_1 - 0.148731395602226;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 0.2707690096878486700000000;
	a += age_2 * -0.0178911237651764690000000;
	a += bmi_1 * 5.7829320185166670000000000;

	/* Sum from boolean values */

	a += b_antidepressant * 0.3327369489309151000000000;
	a += b_anycancer * 0.2685285338413267400000000;
	a += b_asthmacopd * 0.2109878042448810100000000;
	a += b_corticosteroids * 0.1700600172324418800000000;
	a += b_cvd * 0.2023318326470322500000000;
	a += b_dementia * 0.9427384234437306000000000;
	a += b_endocrine * 0.2873219609276543900000000;
	a += b_epilepsy2 * 0.4800826666037592000000000;
	a += b_falls * 0.4341031983222869400000000;
	a += b_fracture4 * 0.5498089896441453700000000;
	a += b_hrt_oest * -0.2717838245725980300000000;
	a += b_liver * 0.6449388096998517300000000;
	a += b_parkinsons * 0.7086700991849171900000000;
	a += b_ra_sle * 0.5226829686337491900000000;
	a += b_renal * 0.4121883090139577500000000;
	a += b_type1 * 1.5320881578751737000000000;
	a += b_type2 * 0.4487045379402456700000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int nof_female_validation(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_fracture4,int b_hrt_oest,int b_liver,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int smoke_cat,int surv,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,30,100)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (30,100)\n",errorBufSize);
	}
	if (!i_in_range(alcohol_cat6,0,5)) {
		ok=0;
		strlcat(errorBuf,"error: alcohol_cat6 must be in range (0,5)\n",errorBufSize);
	}
	if (!is_boolean(b_antidepressant)) {
		ok=0;
		strlcat(errorBuf,"error: b_antidepressant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_anycancer)) {
		ok=0;
		strlcat(errorBuf,"error: b_anycancer must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_asthmacopd)) {
		ok=0;
		strlcat(errorBuf,"error: b_asthmacopd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_corticosteroids)) {
		ok=0;
		strlcat(errorBuf,"error: b_corticosteroids must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_cvd)) {
		ok=0;
		strlcat(errorBuf,"error: b_cvd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_dementia)) {
		ok=0;
		strlcat(errorBuf,"error: b_dementia must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_endocrine)) {
		ok=0;
		strlcat(errorBuf,"error: b_endocrine must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_epilepsy2)) {
		ok=0;
		strlcat(errorBuf,"error: b_epilepsy2 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_falls)) {
		ok=0;
		strlcat(errorBuf,"error: b_falls must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_fracture4)) {
		ok=0;
		strlcat(errorBuf,"error: b_fracture4 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_hrt_oest)) {
		ok=0;
		strlcat(errorBuf,"error: b_hrt_oest must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_liver)) {
		ok=0;
		strlcat(errorBuf,"error: b_liver must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_parkinsons)) {
		ok=0;
		strlcat(errorBuf,"error: b_parkinsons must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_ra_sle)) {
		ok=0;
		strlcat(errorBuf,"error: b_ra_sle must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type1)) {
		ok=0;
		strlcat(errorBuf,"error: b_type1 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type2)) {
		ok=0;
		strlcat(errorBuf,"error: b_type2 must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,18)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,18)\n",errorBufSize);
	}
	return ok;
}

double nof_female(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_fracture4,int b_hrt_oest,int b_liver,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int smoke_cat,int surv,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = nof_female_validation(age,alcohol_cat6,b_antidepressant,b_anycancer,b_asthmacopd,b_corticosteroids,b_cvd,b_dementia,b_endocrine,b_epilepsy2,b_falls,b_fracture4,b_hrt_oest,b_liver,b_parkinsons,b_ra_sle,b_renal,b_type1,b_type2,bmi,ethrisk,smoke_cat,surv,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return nof_female_raw(age,alcohol_cat6,b_antidepressant,b_anycancer,b_asthmacopd,b_corticosteroids,b_cvd,b_dementia,b_endocrine,b_epilepsy2,b_falls,b_fracture4,b_hrt_oest,b_liver,b_parkinsons,b_ra_sle,b_renal,b_type1,b_type2,bmi,ethrisk,smoke_cat,surv);
}
