/* 
 * Copyright 2012 ClinRisk Ltd.
 * 
 * This file is part of QFracture-2012 (http://qfracture.org, http://svn.clinrisk.co.uk/qfracture).
 * 
 * QFracture-2012 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QFracture-2012 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QFracture-2012.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/qfracture, faithfully implements QFracture-2012.
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/qfracture.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q74_qfracture4_2012_2_1.xml
 * STATA dta time stamp: 1 Mar 2012 11:21
 * This file was created on: Mon  5 Mar 2012 11:14:11 GMT
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q74_qfracture4_2012_2_1.h>
#include <clinrisk/utils.h>

static double fracture4_male_raw(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_carehome,int b_corticosteroids,int b_cvd,int b_dementia,int b_epilepsy2,int b_falls,int b_fracture4,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv
)
{
	double survivor[19] = {
		0,
		0.999644935131073,
		0.999273777008057,
		0.998869180679321,
		0.998421549797058,
		0.997928738594055,
		0.997390747070313,
		0.996753513813019,
		0.996096074581146,
		0.995346963405609,
		0.994551837444305,
		0.993598461151123,
		0.992581725120544,
		0.991482257843018,
		0.990263521671295,
		0.989037752151489,
		0.987761437892914,
		0.986425399780273,
		0.984853565692902
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		-0.0753424993511384030000000,
		0.0035640920160520625000000,
		0.1107180929467958700000000,
		0.2772772729818878100000000,
		0.7629384134280495800000000
	};
	double Iethrisk[10] = {
		0,
		0,
		-0.2578247985190295600000000,
		-0.2739691601862618800000000,
		-1.2488100943578264000000000,
		-0.4478136903122282900000000,
		-0.9569833717832930700000000,
		-0.6454670770263975000000000,
		-0.2441668713268753100000000,
		-0.5585671879728931800000000
	};
	double Ismoke[5] = {
		0,
		-0.0008039513520016420400000,
		0.1560272763218023000000000,
		0.2511740981322320700000000,
		0.2796740114008822700000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,0.5);
	double age_2 = dage;
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-1);
	double bmi_2 = pow(dbmi,-0.5);

	/* Centring the continuous variables */

	age_1 = age_1 - 2.213409662246704;
	age_2 = age_2 - 4.899182319641113;
	bmi_1 = bmi_1 - 0.376987010240555;
	bmi_2 = bmi_2 - 0.613992691040039;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * -9.0010590056070825000000000;
	a += age_2 * 2.4013416577413533000000000;
	a += bmi_1 * 18.1789865484634670000000000;
	a += bmi_2 * -18.9164740466035500000000000;

	/* Sum from boolean values */

	a += b_antidepressant * 0.4687193755788741600000000;
	a += b_anycancer * 0.4507500533865196300000000;
	a += b_asthmacopd * 0.2886693311011971400000000;
	a += b_carehome * 0.4624017599741130900000000;
	a += b_corticosteroids * 0.2959070482702296200000000;
	a += b_cvd * 0.2342575101174369000000000;
	a += b_dementia * 0.6410107589079159200000000;
	a += b_epilepsy2 * 0.7821394592420207700000000;
	a += b_falls * 0.5427801687901475700000000;
	a += b_fracture4 * 0.3037648317094442400000000;
	a += b_liver * 0.9492983471493211500000000;
	a += b_malabsorption * 0.2198043397723023800000000;
	a += b_parkinsons * 0.8971315042849318200000000;
	a += b_ra_sle * 0.4403191212798893100000000;
	a += b_renal * 0.4565029417822387700000000;
	a += b_type1 * 0.8447272010743575000000000;
	a += b_type2 * 0.2219385025905733500000000;
	a += fh_osteoporosis * 1.6999403855072708000000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int fracture4_male_validation(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_carehome,int b_corticosteroids,int b_cvd,int b_dementia,int b_epilepsy2,int b_falls,int b_fracture4,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,30,100)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (30,100)\n",errorBufSize);
	}
	if (!i_in_range(alcohol_cat6,0,5)) {
		ok=0;
		strlcat(errorBuf,"error: alcohol_cat6 must be in range (0,5)\n",errorBufSize);
	}
	if (!is_boolean(b_antidepressant)) {
		ok=0;
		strlcat(errorBuf,"error: b_antidepressant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_anycancer)) {
		ok=0;
		strlcat(errorBuf,"error: b_anycancer must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_asthmacopd)) {
		ok=0;
		strlcat(errorBuf,"error: b_asthmacopd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_carehome)) {
		ok=0;
		strlcat(errorBuf,"error: b_carehome must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_corticosteroids)) {
		ok=0;
		strlcat(errorBuf,"error: b_corticosteroids must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_cvd)) {
		ok=0;
		strlcat(errorBuf,"error: b_cvd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_dementia)) {
		ok=0;
		strlcat(errorBuf,"error: b_dementia must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_epilepsy2)) {
		ok=0;
		strlcat(errorBuf,"error: b_epilepsy2 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_falls)) {
		ok=0;
		strlcat(errorBuf,"error: b_falls must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_fracture4)) {
		ok=0;
		strlcat(errorBuf,"error: b_fracture4 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_liver)) {
		ok=0;
		strlcat(errorBuf,"error: b_liver must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_malabsorption)) {
		ok=0;
		strlcat(errorBuf,"error: b_malabsorption must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_parkinsons)) {
		ok=0;
		strlcat(errorBuf,"error: b_parkinsons must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_ra_sle)) {
		ok=0;
		strlcat(errorBuf,"error: b_ra_sle must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type1)) {
		ok=0;
		strlcat(errorBuf,"error: b_type1 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type2)) {
		ok=0;
		strlcat(errorBuf,"error: b_type2 must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!is_boolean(fh_osteoporosis)) {
		ok=0;
		strlcat(errorBuf,"error: fh_osteoporosis must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,18)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,18)\n",errorBufSize);
	}
	return ok;
}

double fracture4_male(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_carehome,int b_corticosteroids,int b_cvd,int b_dementia,int b_epilepsy2,int b_falls,int b_fracture4,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = fracture4_male_validation(age,alcohol_cat6,b_antidepressant,b_anycancer,b_asthmacopd,b_carehome,b_corticosteroids,b_cvd,b_dementia,b_epilepsy2,b_falls,b_fracture4,b_liver,b_malabsorption,b_parkinsons,b_ra_sle,b_renal,b_type1,b_type2,bmi,ethrisk,fh_osteoporosis,smoke_cat,surv,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return fracture4_male_raw(age,alcohol_cat6,b_antidepressant,b_anycancer,b_asthmacopd,b_carehome,b_corticosteroids,b_cvd,b_dementia,b_epilepsy2,b_falls,b_fracture4,b_liver,b_malabsorption,b_parkinsons,b_ra_sle,b_renal,b_type1,b_type2,bmi,ethrisk,fh_osteoporosis,smoke_cat,surv);
}
