/* 
 * Copyright 2012 ClinRisk Ltd.
 * 
 * This file is part of QFracture-2012 (http://qfracture.org, http://svn.clinrisk.co.uk/qfracture).
 * 
 * QFracture-2012 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QFracture-2012 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QFracture-2012.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/qfracture, faithfully implements QFracture-2012.
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/qfracture.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q74_qfracture4_2012_2_0.xml
 * STATA dta time stamp: 1 Mar 2012 11:21
 * This file was created on: Mon  5 Mar 2012 11:13:59 GMT
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q74_qfracture4_2012_2_0.h>
#include <clinrisk/utils.h>

static double fracture4_female_raw(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_fracture4,int b_hrt_oest,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv
)
{
	double survivor[19] = {
		0,
		0.998989343643188,
		0.997853457927704,
		0.996573925018311,
		0.995212137699127,
		0.993696928024292,
		0.991993606090546,
		0.990109741687775,
		0.988066852092743,
		0.985876500606537,
		0.983377099037170,
		0.980558633804321,
		0.977307498455048,
		0.974049806594849,
		0.970507681369781,
		0.966851711273193,
		0.962773561477661,
		0.958411157131195,
		0.953392088413239
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		0.0002414945264996203800000,
		0.0531971614510470740000000,
		0.1624289372927301400000000,
		0.4778223231666232600000000,
		0.6270597140515218300000000
	};
	double Iethrisk[10] = {
		0,
		0,
		-0.2875917367450486200000000,
		-0.7824524516248326800000000,
		-0.8172794063622931300000000,
		-0.5861737865251788200000000,
		-1.4935356591327420000000000,
		-0.7355039455837261200000000,
		-0.4900951523299932300000000,
		-0.4546040850271730900000000
	};
	double Ismoke[5] = {
		0,
		0.0371938876652497460000000,
		0.0951525414150192620000000,
		0.1221740242710975300000000,
		0.1611412668468513200000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,2);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-1);

	/* Centring the continuous variables */

	age_1 = age_1 - 26.453824996948242;
	age_2 = age_2 - 136.060699462890620;
	bmi_1 = bmi_1 - 0.385703802108765;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * 0.1437995480730194500000000;
	a += age_2 * -0.0093249719419669745000000;
	a += bmi_1 * 2.9094622051196999000000000;

	/* Sum from boolean values */

	a += b_antidepressant * 0.3175542392827512800000000;
	a += b_anycancer * 0.2384763167407743000000000;
	a += b_asthmacopd * 0.2389060345873167400000000;
	a += b_corticosteroids * 0.1926383637036637200000000;
	a += b_cvd * 0.1914278981809385300000000;
	a += b_dementia * 0.6757597945847583200000000;
	a += b_endocrine * 0.2105749527624362900000000;
	a += b_epilepsy2 * 0.4297240630789712600000000;
	a += b_falls * 0.4505018230780948300000000;
	a += b_fracture4 * 0.0804836468689180270000000;
	a += b_hrt_oest * -0.1586145398766347600000000;
	a += b_liver * 0.6391726322367494700000000;
	a += b_malabsorption * 0.1547851620897652300000000;
	a += b_parkinsons * 0.4958354577680105800000000;
	a += b_ra_sle * 0.2888701063403104600000000;
	a += b_renal * 0.2390562428559968600000000;
	a += b_type1 * 0.6523717632491761200000000;
	a += b_type2 * 0.2355143698342233000000000;
	a += fh_osteoporosis * 0.5517999076133333100000000;

	/* Sum from interaction terms */


	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int fracture4_female_validation(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_fracture4,int b_hrt_oest,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,30,100)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (30,100)\n",errorBufSize);
	}
	if (!i_in_range(alcohol_cat6,0,5)) {
		ok=0;
		strlcat(errorBuf,"error: alcohol_cat6 must be in range (0,5)\n",errorBufSize);
	}
	if (!is_boolean(b_antidepressant)) {
		ok=0;
		strlcat(errorBuf,"error: b_antidepressant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_anycancer)) {
		ok=0;
		strlcat(errorBuf,"error: b_anycancer must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_asthmacopd)) {
		ok=0;
		strlcat(errorBuf,"error: b_asthmacopd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_corticosteroids)) {
		ok=0;
		strlcat(errorBuf,"error: b_corticosteroids must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_cvd)) {
		ok=0;
		strlcat(errorBuf,"error: b_cvd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_dementia)) {
		ok=0;
		strlcat(errorBuf,"error: b_dementia must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_endocrine)) {
		ok=0;
		strlcat(errorBuf,"error: b_endocrine must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_epilepsy2)) {
		ok=0;
		strlcat(errorBuf,"error: b_epilepsy2 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_falls)) {
		ok=0;
		strlcat(errorBuf,"error: b_falls must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_fracture4)) {
		ok=0;
		strlcat(errorBuf,"error: b_fracture4 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_hrt_oest)) {
		ok=0;
		strlcat(errorBuf,"error: b_hrt_oest must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_liver)) {
		ok=0;
		strlcat(errorBuf,"error: b_liver must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_malabsorption)) {
		ok=0;
		strlcat(errorBuf,"error: b_malabsorption must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_parkinsons)) {
		ok=0;
		strlcat(errorBuf,"error: b_parkinsons must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_ra_sle)) {
		ok=0;
		strlcat(errorBuf,"error: b_ra_sle must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type1)) {
		ok=0;
		strlcat(errorBuf,"error: b_type1 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type2)) {
		ok=0;
		strlcat(errorBuf,"error: b_type2 must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!is_boolean(fh_osteoporosis)) {
		ok=0;
		strlcat(errorBuf,"error: fh_osteoporosis must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,18)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,18)\n",errorBufSize);
	}
	return ok;
}

double fracture4_female(
int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_fracture4,int b_hrt_oest,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = fracture4_female_validation(age,alcohol_cat6,b_antidepressant,b_anycancer,b_asthmacopd,b_corticosteroids,b_cvd,b_dementia,b_endocrine,b_epilepsy2,b_falls,b_fracture4,b_hrt_oest,b_liver,b_malabsorption,b_parkinsons,b_ra_sle,b_renal,b_type1,b_type2,bmi,ethrisk,fh_osteoporosis,smoke_cat,surv,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return fracture4_female_raw(age,alcohol_cat6,b_antidepressant,b_anycancer,b_asthmacopd,b_corticosteroids,b_cvd,b_dementia,b_endocrine,b_epilepsy2,b_falls,b_fracture4,b_hrt_oest,b_liver,b_malabsorption,b_parkinsons,b_ra_sle,b_renal,b_type1,b_type2,bmi,ethrisk,fh_osteoporosis,smoke_cat,surv);
}
