/* 
 * Copyright 2014 ClinRisk Ltd.
 * 
 * This file is part of QBleed (http://qbleed.org, http://svn.clinrisk.co.uk/opensource/qbleed).
 * 
 * QBleed is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QBleed is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QBleed.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qbleed, faithfully implements QBleed.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qbleed.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q81_anticoagbleed_8_27_3_1.xml
 * STATA dta time stamp: 25 Jan 2014 20:52
 * This file was created on: Tue 29 Jul 2014 14:05:51 BST
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q81_anticoagbleed_8_27_3_1.h>
#include <clinrisk/utils.h>

static double Q81_anticoagbleed_8_27_3_male_raw(
int age,int alcohol_cat6,int b_AF,int b_anticonvulsant,int b_antidepressant,int b_antiplat,int b_liverpancreas,int b_platlet,int b_treatedhyp,int b_varices,double bmi,int ethrisk,int exp_anticoagulant,int prior_anybleed,int smoke_cat,int surv,double town
)
{
	double survivor[6] = {
		0,
		0.999811053276062,
		0,
		0,
		0,
		0.998913109302521
	};

	/* The conditional arrays */

	double Ialcohol[6] = {
		0,
		-0.1728231210094232600000000,
		-0.1647777896022948300000000,
		-0.0307338037098927390000000,
		0.4562194493697658800000000,
		0.3910785488652860400000000
	};
	double Iethrisk[10] = {
		0,
		0,
		0.0767194060923420820000000,
		0.0244590357232785450000000,
		0.1390257367105856800000000,
		0.3678153463842137600000000,
		0.2755679450682267900000000,
		0.4469846553223611500000000,
		0.1371500662488111800000000,
		0.0173683831011310460000000
	};
	double Ismoke[5] = {
		0,
		0.0418592490887348540000000,
		0.3652512695580488200000000,
		0.5414523122027329300000000,
		0.5403190049949365700000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,-1);
	double age_2 = pow(dage,3);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-2);
	double bmi_2 = pow(dbmi,-2)*log(dbmi);

	/* Centring the continuous variables */

	age_1 = age_1 - 0.221857503056526;
	age_2 = age_2 - 91.575149536132812;
	bmi_1 = bmi_1 - 0.146589592099190;
	bmi_2 = bmi_2 - 0.140734687447548;
	town = town - 0.309476047754288;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Ialcohol[alcohol_cat6];
	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * -5.2507346086010047000000000;
	a += age_2 * 0.0037625177105650811000000;
	a += bmi_1 * 4.4559966384591476000000000;
	a += bmi_2 * -5.1549284619476401000000000;
	a += town * 0.0217882468511014890000000;

	/* Sum from boolean values */

	a += b_AF * 0.3063515805216366900000000;
	a += b_anticonvulsant * 0.7096560602093697800000000;
	a += b_antidepressant * 0.3215934336924187200000000;
	a += b_antiplat * 0.2357530027598678800000000;
	a += b_liverpancreas * 0.7930297470683660400000000;
	a += b_platlet * 0.4743303884978551900000000;
	a += b_treatedhyp * 0.1613016519634809000000000;
	a += b_varices * 0.5414304495012054500000000;
	a += exp_anticoagulant * 1.3841065886088877000000000;
	a += prior_anybleed * 0.2762793125632718200000000;

	/* Sum from interaction terms */

	a += age_1 * exp_anticoagulant * -1.3621108691213160000000000;
	a += age_2 * exp_anticoagulant * -0.0012348714453322572000000;

	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int Q81_anticoagbleed_8_27_3_male_validation(
int age,int alcohol_cat6,int b_AF,int b_anticonvulsant,int b_antidepressant,int b_antiplat,int b_liverpancreas,int b_platlet,int b_treatedhyp,int b_varices,double bmi,int ethrisk,int exp_anticoagulant,int prior_anybleed,int smoke_cat,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,21,99)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (21,99)\n",errorBufSize);
	}
	if (!i_in_range(alcohol_cat6,0,5)) {
		ok=0;
		strlcat(errorBuf,"error: alcohol_cat6 must be in range (0,5)\n",errorBufSize);
	}
	if (!is_boolean(b_AF)) {
		ok=0;
		strlcat(errorBuf,"error: b_AF must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_anticonvulsant)) {
		ok=0;
		strlcat(errorBuf,"error: b_anticonvulsant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_antidepressant)) {
		ok=0;
		strlcat(errorBuf,"error: b_antidepressant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_antiplat)) {
		ok=0;
		strlcat(errorBuf,"error: b_antiplat must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_liverpancreas)) {
		ok=0;
		strlcat(errorBuf,"error: b_liverpancreas must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_platlet)) {
		ok=0;
		strlcat(errorBuf,"error: b_platlet must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_treatedhyp)) {
		ok=0;
		strlcat(errorBuf,"error: b_treatedhyp must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_varices)) {
		ok=0;
		strlcat(errorBuf,"error: b_varices must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!is_boolean(exp_anticoagulant)) {
		ok=0;
		strlcat(errorBuf,"error: exp_anticoagulant must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(prior_anybleed)) {
		ok=0;
		strlcat(errorBuf,"error: prior_anybleed must be in range (0,1)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if ( !(surv==1 || surv==5) ) {
		ok=0;
		strlcat(errorBuf,"error: surv must be 1 or 5\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double Q81_anticoagbleed_8_27_3_male(
int age,int alcohol_cat6,int b_AF,int b_anticonvulsant,int b_antidepressant,int b_antiplat,int b_liverpancreas,int b_platlet,int b_treatedhyp,int b_varices,double bmi,int ethrisk,int exp_anticoagulant,int prior_anybleed,int smoke_cat,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = Q81_anticoagbleed_8_27_3_male_validation(age,alcohol_cat6,b_AF,b_anticonvulsant,b_antidepressant,b_antiplat,b_liverpancreas,b_platlet,b_treatedhyp,b_varices,bmi,ethrisk,exp_anticoagulant,prior_anybleed,smoke_cat,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return Q81_anticoagbleed_8_27_3_male_raw(age,alcohol_cat6,b_AF,b_anticonvulsant,b_antidepressant,b_antiplat,b_liverpancreas,b_platlet,b_treatedhyp,b_varices,bmi,ethrisk,exp_anticoagulant,prior_anybleed,smoke_cat,surv,town);
}
