/*
 * Copyright 2013 ClinRisk Ltd.
 *
 * This file is part of QCancer-2013 (http://qcancer.org, http://svn.clinrisk.co.uk/opensource/qcancer).
 *
 * QCancer-2013 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QCancer-2013 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with QCancer-2013.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Additional terms
 *
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qcancer, faithfully implements QCancer-2013.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qcancer.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q76_cancer2_15_1.xml
 * STATA dta time stamp: 27 Aug 2012 13:27
 * This file was created on: Thu 27 Jun 2013 09:04:34 BST
 */

#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <math.h>
#include "Q76_cancer2_15_1.h"

static char errorBuf[1024];
static int error;
#define RESULTS_ARRAY_SIZE 100
static double resultsArray[RESULTS_ARRAY_SIZE];

void usage(void) {
	printf(" * Copyright 2013 ClinRisk Ltd.\n");
	printf(" * \n");
	printf(" * This is part of QCancer-2013 (http://qcancer.org, http://svn.clinrisk.co.uk/opensource/qcancer).\n");
	printf(" * \n");
	printf(" * QCancer-2013 is free software: you can redistribute it and/or modify\n");
	printf(" * it under the terms of the GNU Lesser General Public License as published by\n");
	printf(" * the Free Software Foundation, either version 3 of the License, or\n");
	printf(" * (at your option) any later version.\n");
	printf(" * \n");
	printf(" * QCancer-2013 is distributed in the hope that it will be useful,\n");
	printf(" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
	printf(" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n");
	printf(" * GNU Lesser General Public License for more details.\n");
	printf(" * \n");
	printf(" * You should have received a copy of the GNU Lesser General Public License\n");
	printf(" * along with QCancer-2013.  If not, see <http://www.gnu.org/licenses/>.\n");
	printf(" * \n");
	printf(" * The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qcancer, faithfully implements QCancer-2013.\n");
	printf(" * We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.\n");
	printf(" * However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.\n");
	printf(" * We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qcancer.\n");
	printf(" * Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.\n");
	printf(" *\n");
	printf(" * This file has been auto-generated.\n");
	printf(" * XML source: Q76_cancer2_15_1.xml\n");
	printf(" * STATA dta time stamp: 27 Aug 2012 13:27\n");
	printf(" * C file create date: Thu 27 Jun 2013 09:04:34 BST\n");
	printf(" *\n");
	printf("Usage:\n");
	printf("  Q76_cancer2_15_1_commandLine age alcohol_cat4 b_chronicpan b_copd b_type2 bmi c_hb fh_gicancer fh_prostatecancer new_abdodist new_abdopain new_appetiteloss new_dysphagia new_gibleed new_haematuria new_haemoptysis new_heartburn new_indigestion new_necklump new_nightsweats new_rectalbleed new_testespain new_testicularlump new_vte new_weightloss s1_bowelchange s1_constipation s1_cough s1_impotence s1_nocturia s1_urinaryfreq s1_urinaryretention smoke_cat town\n");
}

void calculateAllScores(int age,int alcohol_cat4,int b_chronicpan,int b_copd,int b_type2,double bmi,int c_hb,int fh_gicancer,int fh_prostatecancer,int new_abdodist,int new_abdopain,int new_appetiteloss,int new_dysphagia,int new_gibleed,int new_haematuria,int new_haemoptysis,int new_heartburn,int new_indigestion,int new_necklump,int new_nightsweats,int new_rectalbleed,int new_testespain,int new_testicularlump,int new_vte,int new_weightloss,int s1_bowelchange,int s1_constipation,int s1_cough,int s1_impotence,int s1_nocturia,int s1_urinaryfreq,int s1_urinaryretention,int smoke_cat,double town) {
	double sum = 1;
	int i = 1;

	if (10 > RESULTS_ARRAY_SIZE) {
		printf("There are more outcomes that space in the results array.  Re-compile needed.");
		exit(1);
	}

	double blood_cancer_score = blood_cancer_male(age,bmi,c_hb,new_abdodist,new_abdopain,new_appetiteloss,new_dysphagia,new_haematuria,new_haemoptysis,new_indigestion,new_necklump,new_nightsweats,new_testicularlump,new_vte,new_weightloss,town,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("blood_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(blood_cancer_score);
	sum += resultsArray[i++];

	double colorectal_cancer_score = colorectal_cancer_male(age,alcohol_cat4,bmi,c_hb,fh_gicancer,new_abdodist,new_abdopain,new_appetiteloss,new_rectalbleed,new_weightloss,s1_bowelchange,s1_constipation,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("colorectal_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(colorectal_cancer_score);
	sum += resultsArray[i++];

	double gastro_oesophageal_cancer_score = gastro_oesophageal_cancer_male(age,bmi,c_hb,new_abdopain,new_appetiteloss,new_dysphagia,new_gibleed,new_heartburn,new_indigestion,new_necklump,new_weightloss,smoke_cat,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("gastro_oesophageal_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(gastro_oesophageal_cancer_score);
	sum += resultsArray[i++];

	double lung_cancer_score = lung_cancer_male(age,b_copd,bmi,c_hb,new_abdopain,new_appetiteloss,new_dysphagia,new_haemoptysis,new_indigestion,new_necklump,new_nightsweats,new_vte,new_weightloss,s1_cough,smoke_cat,town,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("lung_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(lung_cancer_score);
	sum += resultsArray[i++];

	double other_cancer_score = other_cancer_male(age,b_copd,b_type2,bmi,c_hb,new_abdodist,new_abdopain,new_appetiteloss,new_dysphagia,new_gibleed,new_haematuria,new_haemoptysis,new_indigestion,new_necklump,new_vte,new_weightloss,s1_bowelchange,s1_constipation,smoke_cat,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("other_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(other_cancer_score);
	sum += resultsArray[i++];

	double pancreatic_cancer_score = pancreatic_cancer_male(age,b_chronicpan,b_type2,bmi,new_abdopain,new_appetiteloss,new_dysphagia,new_gibleed,new_indigestion,new_vte,new_weightloss,s1_constipation,smoke_cat,town,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("pancreatic_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(pancreatic_cancer_score);
	sum += resultsArray[i++];

	double prostate_cancer_score = prostate_cancer_male(age,bmi,fh_prostatecancer,new_abdopain,new_appetiteloss,new_haematuria,new_rectalbleed,new_testespain,new_testicularlump,new_vte,new_weightloss,s1_impotence,s1_nocturia,s1_urinaryfreq,s1_urinaryretention,town,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("prostate_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(prostate_cancer_score);
	sum += resultsArray[i++];

	double renal_tract_cancer_score = renal_tract_cancer_male(age,bmi,new_abdopain,new_haematuria,new_nightsweats,new_weightloss,smoke_cat,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("renal_tract_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(renal_tract_cancer_score);
	sum += resultsArray[i++];

	double testicular_cancer_score = testicular_cancer_male(age,bmi,new_testespain,new_testicularlump,new_vte,&error,errorBuf,sizeof(errorBuf));
	if (error) {
		printf("testicular_cancer:\n%s", errorBuf);
		exit(1);
	}
	resultsArray[i] = exp(testicular_cancer_score);
	sum += resultsArray[i++];

	/*  normalise each score and express it as a percentage */

	double sum2;
	for (i=1, sum2=0; i< 10; i++) {
		resultsArray[i] *= 100 / sum;
		sum2 += resultsArray[i];
	}

	/*  Add the risk of no event to the start of the result array */
	resultsArray[0] = 100 - sum2;
}
int main (int argc, char *argv[]) {
	if (argc!=35) {
		usage();
		exit(1);
	}

	int age = strtol(argv[1],NULL,0);
	int alcohol_cat4 = strtol(argv[2],NULL,0);
	int b_chronicpan = strtol(argv[3],NULL,0);
	int b_copd = strtol(argv[4],NULL,0);
	int b_type2 = strtol(argv[5],NULL,0);
	double bmi = strtod(argv[6],NULL);
	int c_hb = strtol(argv[7],NULL,0);
	int fh_gicancer = strtol(argv[8],NULL,0);
	int fh_prostatecancer = strtol(argv[9],NULL,0);
	int new_abdodist = strtol(argv[10],NULL,0);
	int new_abdopain = strtol(argv[11],NULL,0);
	int new_appetiteloss = strtol(argv[12],NULL,0);
	int new_dysphagia = strtol(argv[13],NULL,0);
	int new_gibleed = strtol(argv[14],NULL,0);
	int new_haematuria = strtol(argv[15],NULL,0);
	int new_haemoptysis = strtol(argv[16],NULL,0);
	int new_heartburn = strtol(argv[17],NULL,0);
	int new_indigestion = strtol(argv[18],NULL,0);
	int new_necklump = strtol(argv[19],NULL,0);
	int new_nightsweats = strtol(argv[20],NULL,0);
	int new_rectalbleed = strtol(argv[21],NULL,0);
	int new_testespain = strtol(argv[22],NULL,0);
	int new_testicularlump = strtol(argv[23],NULL,0);
	int new_vte = strtol(argv[24],NULL,0);
	int new_weightloss = strtol(argv[25],NULL,0);
	int s1_bowelchange = strtol(argv[26],NULL,0);
	int s1_constipation = strtol(argv[27],NULL,0);
	int s1_cough = strtol(argv[28],NULL,0);
	int s1_impotence = strtol(argv[29],NULL,0);
	int s1_nocturia = strtol(argv[30],NULL,0);
	int s1_urinaryfreq = strtol(argv[31],NULL,0);
	int s1_urinaryretention = strtol(argv[32],NULL,0);
	int smoke_cat = strtol(argv[33],NULL,0);
	double town = strtod(argv[34],NULL);

	if (errno) {
		printf("At least one of the parameters was not a number!\n");
		exit(1);
	}

	calculateAllScores(age,alcohol_cat4,b_chronicpan,b_copd,b_type2,bmi,c_hb,fh_gicancer,fh_prostatecancer,new_abdodist,new_abdopain,new_appetiteloss,new_dysphagia,new_gibleed,new_haematuria,new_haemoptysis,new_heartburn,new_indigestion,new_necklump,new_nightsweats,new_rectalbleed,new_testespain,new_testicularlump,new_vte,new_weightloss,s1_bowelchange,s1_constipation,s1_cough,s1_impotence,s1_nocturia,s1_urinaryfreq,s1_urinaryretention,smoke_cat,town);

	/* print the scores */

	printf("none,blood_cancer,colorectal_cancer,gastro_oesophageal_cancer,lung_cancer,other_cancer,pancreatic_cancer,prostate_cancer,renal_tract_cancer,testicular_cancer\n");
	int i;
	for (i=0;i<8+1;i++) {
		printf("%f,",resultsArray[i]);
	}
	printf("%f\n",resultsArray[i]);
}
