/*
 * Copyright 2013 ClinRisk Ltd.
 *
 * This file is part of QCancer-2013 (http://qcancer.org, http://svn.clinrisk.co.uk/opensource/qcancer).
 *
 * QCancer-2013 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QCancer-2013 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with QCancer-2013.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Additional terms
 *
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qcancer, faithfully implements QCancer-2013.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qcancer.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q76_cancer2_16_0.xml
 * STATA dta time stamp: 27 Aug 2012 13:27
 * This file was created on: Thu 27 Jun 2013 09:06:56 BST
 */

double blood_cancer_female(
int age,double bmi,int c_hb,int new_abdopain,int new_haematuria,int new_necklump,int new_nightsweats,int new_pmb,int new_vte,int new_weightloss,int s1_bowelchange,int s1_bruising,int *error,char *errorBuf,int errorBufSize
);
double breast_cancer_female(
int age,int alcohol_cat4,double bmi,int fh_breastcancer,int new_breastlump,int new_breastpain,int new_breastskin,int new_pmb,int new_vte,double town,int *error,char *errorBuf,int errorBufSize
);
double cervical_cancer_female(
int age,double bmi,int c_hb,int new_abdopain,int new_haematuria,int new_imb,int new_pmb,int new_postcoital,int new_vte,int smoke_cat,double town,int *error,char *errorBuf,int errorBufSize
);
double colorectal_cancer_female(
int age,int alcohol_cat4,double bmi,int c_hb,int fh_gicancer,int new_abdodist,int new_abdopain,int new_appetiteloss,int new_rectalbleed,int new_vte,int new_weightloss,int s1_bowelchange,int s1_constipation,int *error,char *errorBuf,int errorBufSize
);
double gastro_oesophageal_cancer_female(
int age,double bmi,int c_hb,int new_abdopain,int new_appetiteloss,int new_dysphagia,int new_gibleed,int new_heartburn,int new_indigestion,int new_vte,int new_weightloss,int smoke_cat,int *error,char *errorBuf,int errorBufSize
);
double lung_cancer_female(
int age,int b_copd,double bmi,int c_hb,int new_appetiteloss,int new_dysphagia,int new_haemoptysis,int new_indigestion,int new_necklump,int new_vte,int new_weightloss,int s1_cough,int smoke_cat,double town,int *error,char *errorBuf,int errorBufSize
);
double other_cancer_female(
int age,int alcohol_cat4,int b_copd,double bmi,int c_hb,int new_abdodist,int new_abdopain,int new_appetiteloss,int new_breastlump,int new_dysphagia,int new_gibleed,int new_haematuria,int new_indigestion,int new_necklump,int new_pmb,int new_vte,int new_weightloss,int s1_constipation,int smoke_cat,int *error,char *errorBuf,int errorBufSize
);
double ovarian_cancer_female(
int age,double bmi,int c_hb,int fh_ovariancancer,int new_abdodist,int new_abdopain,int new_appetiteloss,int new_haematuria,int new_indigestion,int new_pmb,int new_vte,int new_weightloss,int s1_bowelchange,int *error,char *errorBuf,int errorBufSize
);
double pancreatic_cancer_female(
int age,int b_chronicpan,int b_type2,double bmi,int new_abdopain,int new_appetiteloss,int new_dysphagia,int new_gibleed,int new_indigestion,int new_vte,int new_weightloss,int s1_bowelchange,int smoke_cat,int *error,char *errorBuf,int errorBufSize
);
double renal_tract_cancer_female(
int age,double bmi,int c_hb,int new_abdopain,int new_appetiteloss,int new_haematuria,int new_indigestion,int new_pmb,int new_weightloss,int smoke_cat,int *error,char *errorBuf,int errorBufSize
);
double uterine_cancer_female(
int age,int b_endometrial,int b_type2,double bmi,int new_abdopain,int new_haematuria,int new_imb,int new_pmb,int new_vte,int *error,char *errorBuf,int errorBufSize
);
