/* 
 * Copyright 2012 ClinRisk Ltd.
 * 
 * This file is part of QStroke (http://qstroke.org, http://svn.clinrisk.co.uk/opensource/qstroke).
 * 
 * QStroke is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QStroke is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with QStroke.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qstroke, faithfully implements QStroke.
 *   We have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone altering the coefficients.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qstroke.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * This file has been auto-generated.
 * XML source: Q77_qstroke_19_1.xml
 * STATA dta time stamp: 9 Mar 2013 15:23
 * This file was created on: Sat  9 Mar 2013 16:20:30 GMT
 */

#include <math.h>
#include <string.h>
#include <clinrisk/Q77_qstroke_19_1.h>
#include <clinrisk/utils.h>

static double stroke_male_raw(
int age,int b_AF,int b_CCF,int b_chd,int b_ra,int b_renal,int b_treatedhyp,int b_type1,int b_type2,int b_valvular,double bmi,int ethrisk,int fh_cvd,double rati,double sbp,int smoke_cat,int surv,double town
)
{
	double survivor[16] = {
		0,
		0.999487161636353,
		0.998943150043488,
		0.998373985290527,
		0.997744083404541,
		0.997065007686615,
		0.996341764926910,
		0.995574831962585,
		0.994802832603455,
		0.993988394737244,
		0.993128657341003,
		0.992210268974304,
		0.991193234920502,
		0.990198373794556,
		0.989128828048706,
		0.988554954528809
	};

	/* The conditional arrays */

	double Iethrisk[10] = {
		0,
		0,
		-0.0764368476458289900000000,
		0.0571357655504688010000000,
		0.0750168509341927470000000,
		-0.0255093418294540240000000,
		-0.0196755890137448010000000,
		-0.1747887493090693200000000,
		-0.4099010101086592600000000,
		-0.3078265643907502900000000
	};
	double Ismoke[5] = {
		0,
		0.1552773552459725000000000,
		0.5296226955713869700000000,
		0.5329542987864534000000000,
		0.7249648735764742100000000
	};

	/* Applying the fractional polynomial transforms */
	/* (which includes scaling)                      */

	double dage = age;
	dage=dage/10;
	double age_1 = pow(dage,-1);
	double age_2 = pow(dage,-1)*log(dage);
	double dbmi = bmi;
	dbmi=dbmi/10;
	double bmi_1 = pow(dbmi,-2);
	double bmi_2 = pow(dbmi,-2)*log(dbmi);

	/* Centring the continuous variables */

	age_1 = age_1 - 0.223224431276321;
	age_2 = age_2 - 0.334742367267609;
	bmi_1 = bmi_1 - 0.144959196448326;
	bmi_2 = bmi_2 - 0.139980062842369;
	rati = rati - 4.374470233917236;
	sbp = sbp - 131.996871948242190;
	town = town - -0.014665771275759;

	/* Start of Sum */
	double a=0;

	/* The conditional sums */

	a += Iethrisk[ethrisk];
	a += Ismoke[smoke_cat];

	/* Sum from continuous values */

	a += age_1 * -3.9673936261765470000000000;
	a += age_2 * -39.0347420211951500000000000;
	a += bmi_1 * 5.1085638322885796000000000;
	a += bmi_2 * -10.3408874619570030000000000;
	a += rati * 0.0740254180616774230000000;
	a += sbp * 0.0141266123505316420000000;
	a += town * 0.0410201030054811660000000;

	/* Sum from boolean values */

	a += b_AF * 0.4688956565252527800000000;
	a += b_CCF * 0.8849826595982599500000000;
	a += b_chd * 0.9405469903780190300000000;
	a += b_ra * 0.2165383322630131900000000;
	a += b_renal * 0.3326830725248204300000000;
	a += b_treatedhyp * 0.6116303404347371900000000;
	a += b_type1 * 1.2863652184197687000000000;
	a += b_type2 * 0.6758136449121166000000000;
	a += b_valvular * 0.8767695242359757600000000;
	a += fh_cvd * 0.2555160668352805500000000;

	/* Sum from interaction terms */

	a += age_1 * (smoke_cat==1) * 0.1319310717787916000000000;
	a += age_1 * (smoke_cat==2) * -3.7777100480315955000000000;
	a += age_1 * (smoke_cat==3) * -2.0141772764248631000000000;
	a += age_1 * (smoke_cat==4) * -3.2046066813681535000000000;
	a += age_1 * b_CCF * 16.9738747052129460000000000;
	a += age_1 * b_chd * 13.2310834025785430000000000;
	a += age_1 * b_treatedhyp * 11.4597040046828130000000000;
	a += age_1 * b_type1 * -2.5922675469325065000000000;
	a += age_1 * b_type2 * 2.3309672629845148000000000;
	a += age_1 * b_valvular * -0.5990694384329117200000000;
	a += age_1 * bmi_1 * 11.6370752202834820000000000;
	a += age_1 * bmi_2 * -106.2099990656921900000000000;
	a += age_1 * fh_cvd * 1.6754678961432341000000000;
	a += age_1 * sbp * -0.0525602068113598110000000;
	a += age_1 * town * -0.6221233366101081000000000;
	a += age_2 * (smoke_cat==1) * 1.5734752401338576000000000;
	a += age_2 * (smoke_cat==2) * 10.1004566263405860000000000;
	a += age_2 * (smoke_cat==3) * 5.9354809751853459000000000;
	a += age_2 * (smoke_cat==4) * 9.2403842314780817000000000;
	a += age_2 * b_CCF * -11.7308096828027860000000000;
	a += age_2 * b_chd * -6.4805609091441072000000000;
	a += age_2 * b_treatedhyp * -9.0447741378075630000000000;
	a += age_2 * b_type1 * 16.4496674300914910000000000;
	a += age_2 * b_type2 * 3.2445091076320054000000000;
	a += age_2 * b_valvular * 10.9327837964980700000000000;
	a += age_2 * bmi_1 * 31.2645930525128970000000000;
	a += age_2 * bmi_2 * 32.9081007514201290000000000;
	a += age_2 * fh_cvd * 1.3708144818564409000000000;
	a += age_2 * sbp * 0.2323283327543341500000000;
	a += age_2 * town * 1.4980914447710214000000000;

	/* Calculate the score itself */
	double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
	return score;
}

static int stroke_male_validation(
int age,int b_AF,int b_CCF,int b_chd,int b_ra,int b_renal,int b_treatedhyp,int b_type1,int b_type2,int b_valvular,double bmi,int ethrisk,int fh_cvd,double rati,double sbp,int smoke_cat,int surv,double town,char *errorBuf,int errorBufSize
)
{
	int ok=1;
	*errorBuf=0;
	if (!i_in_range(age,25,84)) {
		ok=0;
		strlcat(errorBuf,"error: age must be in range (25,84)\n",errorBufSize);
	}
	if (!is_boolean(b_AF)) {
		ok=0;
		strlcat(errorBuf,"error: b_AF must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_CCF)) {
		ok=0;
		strlcat(errorBuf,"error: b_CCF must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_chd)) {
		ok=0;
		strlcat(errorBuf,"error: b_chd must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_ra)) {
		ok=0;
		strlcat(errorBuf,"error: b_ra must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_renal)) {
		ok=0;
		strlcat(errorBuf,"error: b_renal must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_treatedhyp)) {
		ok=0;
		strlcat(errorBuf,"error: b_treatedhyp must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type1)) {
		ok=0;
		strlcat(errorBuf,"error: b_type1 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_type2)) {
		ok=0;
		strlcat(errorBuf,"error: b_type2 must be in range (0,1)\n",errorBufSize);
	}
	if (!is_boolean(b_valvular)) {
		ok=0;
		strlcat(errorBuf,"error: b_valvular must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(bmi,20,40)) {
		ok=0;
		strlcat(errorBuf,"error: bmi must be in range (20,40)\n",errorBufSize);
	}
	if (!i_in_range(ethrisk,1,9)) {
		ok=0;
		strlcat(errorBuf,"error: ethrisk must be in range (1,9)\n",errorBufSize);
	}
	if (!is_boolean(fh_cvd)) {
		ok=0;
		strlcat(errorBuf,"error: fh_cvd must be in range (0,1)\n",errorBufSize);
	}
	if (!d_in_range(rati,1,12)) {
		ok=0;
		strlcat(errorBuf,"error: rati must be in range (1,12)\n",errorBufSize);
	}
	if (!d_in_range(sbp,70,210)) {
		ok=0;
		strlcat(errorBuf,"error: sbp must be in range (70,210)\n",errorBufSize);
	}
	if (!i_in_range(smoke_cat,0,4)) {
		ok=0;
		strlcat(errorBuf,"error: smoke_cat must be in range (0,4)\n",errorBufSize);
	}
	if (!i_in_range(surv,1,15)) {
		ok=0;
		strlcat(errorBuf,"error: surv must be in range (1,15)\n",errorBufSize);
	}
	if (!d_in_range(town,-7,11)) {
		ok=0;
		strlcat(errorBuf,"error: town must be in range (-7,11)\n",errorBufSize);
	}
	return ok;
}

double stroke_male(
int age,int b_AF,int b_CCF,int b_chd,int b_ra,int b_renal,int b_treatedhyp,int b_type1,int b_type2,int b_valvular,double bmi,int ethrisk,int fh_cvd,double rati,double sbp,int smoke_cat,int surv,double town,int *error,char *errorBuf,int errorBufSize
)
{
	*error = 0;	int ok = stroke_male_validation(age,b_AF,b_CCF,b_chd,b_ra,b_renal,b_treatedhyp,b_type1,b_type2,b_valvular,bmi,ethrisk,fh_cvd,rati,sbp,smoke_cat,surv,town,errorBuf,errorBufSize);
	if(!ok) { 
		*error = 1;
		return 0.0;
	}
	return stroke_male_raw(age,b_AF,b_CCF,b_chd,b_ra,b_renal,b_treatedhyp,b_type1,b_type2,b_valvular,bmi,ethrisk,fh_cvd,rati,sbp,smoke_cat,surv,town);
}
